### ISSUE TITLE
[BUG] Can't open optimizer in Collab

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki#235]
**Describe the bug**
Error message:
```
Fetch for https://api.github.com/repos/open-spaced-repetition/fsrs4anki/contents/?per_page=100&ref=v3.17.2 failed: {
  "message": "No commit found for the ref v3.17.2",
  "documentation_url": "https://docs.github.com/v3/repos/contents/"
}

CustomError: Fetch for https://api.github.com/repos/open-spaced-repetition/fsrs4anki/contents/?per_page=100&ref=v3.17.2 failed: {
  "message": "No commit found for the ref v3.17.2",
  "documentation_url": "https://docs.github.com/v3/repos/contents/"
}

    at new nI (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:2105:68)
    at ta.program_ (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:2088:435)
    at wa (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:21:57)
    at ta.next_ (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:19:195)
    at laa.next (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:22:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/7eb5b53986a0c4bf9c4183ea7e84af3b/external_polymer_binary.js:22:309)

```

**To Reproduce**
1. Go to https://github.com/open-spaced-repetition/fsrs4anki
2. Click on [fsrs4anki_optimizer.ipynb](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb)
3. Click on "Open in Colab"

**Screenshots**
![image](https://user-images.githubusercontent.com/83031600/235135315-3f8b7047-e8cf-4818-b86d-974f338648a8.png)

**Environment**
 - Optimizer version: v3.17.2

**Comment by L-M-Sherlock** [comment]
It has been released just now.
