### ISSUE TITLE
Can't Reschedule [BUG]

### ISSUE THREAD

**Issue by Elhison** [open-spaced-repetition/fsrs4anki#265]
**Describe the bug**
Error when rescheduling

**To Reproduce**
Reschedule (in any way)

**Expected behavior**
Properly reschedule cards

**Screenshots**
None

**Environment**
 - Anki version: [e.g. 2.1.55]
 - OS: [Linux & iPadOS]
 - Scheduler version: [e.g. v1.0.0]
 - Optimizer version: [e.g. v1.0.3]
 - Simulator version: [e.g. v1.1.0]

**Additional context**
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-6.2.15-300.fc38.x86_64-x86_64-with-glibc2.37
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-20 11:59:45
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/home/chonk/.local/share/Anki2/addons21/759844606/__init__.py", line 46, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "/home/chonk/.local/share/Anki2/addons21/759844606/reschedule.py", line 155, in reschedule
    for cid in mw.col.find_cards(query):
  File "anki.collection", line 630, in find_cards
  File "anki._backend_generated", line 1521, in search_cards
  File "anki._backend", line 156, in _run_command
anki.errors.SearchError: <p>Invalid search: ⁨the escape sequence <code>⁨\o⁩</code> is not defined. If you want to search for a literal backslash <code>\</code>, prepend another one: <code>\\</code>.⁩</p>
```

**Comment by L-M-Sherlock** [comment]
Same as: https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/79#issuecomment-1520080786
