### ISSUE TITLE
[BUG] Error in updating Scheduler and using Rescheduler

### ISSUE THREAD

**Issue by PickeBlind** [open-spaced-repetition/fsrs4anki#355]
**Describe the bug**
After updating the old Scheduler code with the new v4.0.0 version and clicking on 'Reschedule all cards', the error mentioned below appears. Also all rating options show as if the deck was a filtered deck.

**To Reproduce**
1. Replace old Scheduler code with new v4.0.0 version.
2. Click on 'Reschedule all cards'
3. See error

**Expected behavior**
Reschedules the cards based on the new version of the Scheduler. Rating options work as normal.

**Screenshots**
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/28679388/6a023ef7-dec3-4117-b024-d7b99fded5aa)
![image](https://github.com/open-spaced-repetition/fsrs4anki/assets/28679388/6fa6077f-600f-4fe5-83d0-b23150980f8b)

**Environment**
 - Anki version: 2.1.65 Qt5
 - OS: Windows 11
 - Scheduler version: FSRS4Anki v4.0.0 Scheduler Qt5
 - Optimizer version: v4.0.2
 - Simulator version: Not using.

**Additional context**

I am using Optimizer weights generated by the version v4.0.2. The error is listed below.

```
Error

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-07-14 17:28:53

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 141, in on_done
    tooltip(future.result())
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 153, in <lambda>
    fut = mw.taskman.run_in_background(lambda: reschedule_background(did, recent, filter_flag, filtered_cids), on_done)
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 285, in reschedule_background
    again_s = fsrs.next_forget_stability(fsrs.next_difficulty(d, 1), s, r)
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 93, in next_forget_stability
    (math.pow(s + 1, self.w[13]) - 1) *
IndexError: list index out of range
```

**Comment by PickeBlind** [comment]
Problem was solved by using default weights. I suspect i didn't have enough data before running the optimizer previously, not quite sure if i should close the issue.

**Comment by L-M-Sherlock** [comment]
The weights are incompatible between FSRS3 and FSRS4.

**Comment by PickeBlind** [comment]
I see, i was wrong about by assumption then. Thank you for responding!
