### ISSUE TITLE
[BUG] UnboundLocalError: local variable 'nid' referenced before assignment

### ISSUE THREAD

**Issue by DerDemystifier** [open-spaced-repetition/fsrs4anki#441]
**Describe the bug**
I have enabled the "Auto Reschedule card after each review" option. But after the latest update, I'm getting this error.
```error
Error
Debug info:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-27 10:15:15

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 459, in after_answer
  File "aqt.reviewer", line 472, in _after_answering
  File "_aqt.hooks", line 3910, in __call__
  File "D:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\__init__.py", line 9, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease, undo_entry)
  File "D:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 299, in disperse_siblings_when_review
    siblings = get_siblings_when_review(card)
  File "D:\Users\User\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 270, in get_siblings_when_review
    return siblings_dict[nid]
UnboundLocalError: local variable 'nid' referenced before assignment
```

**To Reproduce**
1. Enable "Auto Reschedule card after each review"
2. Review a card.

**Environment**
 - Anki version: 2.1.63
 - OS: Windows 10 64bits
 - Scheduler version: Latest
 - Optimizer version: Latest
 - Simulator version: Latest

**Comment by L-M-Sherlock** [comment]
My fault. I wrote a bug in the latest version. But I'm outside now. I will fix it in 3~4 hours.

**Comment by ApprobationBW** [comment]
Anki 2.1.65 (aa9a734f) Python 3.11.3 Qt 6.5.2 PyQt 6.5.2
Platform: Linux-6.1.47-1-MANJARO-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-08-27 13:44:30
Möglicherweise beteiligte Erweiterungen: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 122, in _on_closures_pending
    closure()
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 71, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 90, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.11/site-packages/aqt/operations/__init__.py", line 125, in wrapped_done
    self._success(result)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 460, in after_answer
    self._after_answering(ease)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 473, in _after_answering
    gui_hooks.reviewer_did_answer_card(self, self.card, ease)
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 3982, in __call__
    hook(reviewer, card, ease)
  File "/home/m/.local/share/Anki2/addons21/759844606/schedule/__init__.py", line 9, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease, undo_entry)
  File "/home/m/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 299, in disperse_siblings_when_review
    siblings = get_siblings_when_review(card)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 270, in get_siblings_when_review
    return siblings_dict[nid]
           ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nid' where it is not associated with a value
`
