### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chokan911** [open-spaced-repetition/fsrs4anki#452]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-05 02:51:04
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 465, in after_answer
  File "aqt.reviewer", line 478, in _after_answering
  File "_aqt.hooks", line 4078, in __call__
  File "C:\Users\Срщлфт\AppData\Roaming\Anki2\addons21\759844606\schedule\__init__.py", line 8, in reschedule_and_disperse_siblings_when_review
    undo_entry = reschedule_when_review(reviewer, card, ease)
  File "C:\Users\Срщлфт\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 365, in reschedule_when_review
    deck_parameters = get_deck_parameters(custom_scheduler)
  File "C:\Users\Срщлфт\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 162, in get_deck_parameters
    weights = _get_weights(version, w_str_matches)
  File "C:\Users\Срщлфт\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 107, in _get_weights
    return [list(map(float, w.split(", "))) for w in str_matches]
  File "C:\Users\Срщлфт\AppData\Roaming\Anki2\addons21\759844606\utils.py", line 107, in <listcomp>
    return [list(map(float, w.split(", "))) for w in str_matches]
ValueError: could not convert string to float: '2.3898]'

**Comment by L-M-Sherlock** [comment]
Please check your parameters of FSRS.

**Comment by L-M-Sherlock** [comment]
I guess you input an extra `]` in the parameters. Please remove it.
