### ISSUE TITLE
[BUG] Raises error when trying to reschedule cards, after updating to v4 scheduler

### ISSUE THREAD

**Issue by olexsmir** [open-spaced-repetition/fsrs4anki#467]
**To Reproduce**
1. Go to 'Tools'
2. Go under 'FSRS4Anki helper'
3. Click on 'reschedule all cards'

**Expected behavior**
Reschedule all cards

**Environment**
 - Anki version: 2.1.65
 - OS: `arch linux` btw
 - Scheduler version: v4.5.6
 - Optimizer version: v4.7.1
 - Simulator version: -

**Additional context**
Today I have **upgraded** to V4 schedules and **regenerated** weights. Now when I try to reschedule/sync cards I get this error

**Error message with debug info**
```
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.4.10-arch1-1-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-18 23:04:40
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/home/olex/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 238, in on_done
    tooltip(future.result())
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/home/olex/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 259, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "/home/olex/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 282, in reschedule_background
    get_skip_decks(custom_scheduler) if geq_version(version, (3, 12, 0)) else []
  File "/home/olex/.local/share/Anki2/addons21/759844606/utils.py", line 260, in get_skip_decks
    names = str_matches[0].split(", ")
IndexError: list index out of range
```

**Comment by olexsmir** [comment]
This all my configuration
```
// Configuration Start
const enable_fuzz = true;
const display_memory_state = false;
const deckParams = [
  {
    // Default parameters of FSRS4Anki for global
    "deckName": "global config for FSRS4Anki",
    "w": [0.307, 1.4953, 4.9881, 7.1931, 5.2435, 1.2191, 1.1269, 0.0453, 1.351, 0.1, 0.7827, 2.1507, 0.0591, 0.2718, 1.4331, 0.3022, 2.1138],
    // The above parameters can be optimized via FSRS4Anki optimizer.
    // For details about the parameters, please see: https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm
    // User's custom parameters for global
    "requestRetention": 0.9, // recommended setting: 0.75 ~ 0.95
    "maximumInterval": 36500, // FSRS only modifies the long-term scheduling. So (re)learning steps in deck options work as usual. I recommend setting steps shorter than 1 day.
  }
];
// Configuration End
```

whole scheduler code [here](https://pastebin.com/3FWKrvcZ)
